print(f"=========================")
print(f"   Best Friend Maker     ")
print(f"=========================")
print()
print(f"Hi. I'm the computer.")
your_name = input("What's your name? ")
favorite_color = input(f"Hi, {your_name}! What's your favorite color? ")
print(f"No way! My favorite color is also {favorite_color} ")
favorite_movie = input("What's your favorite movie? ")
print(f" What!?! My favorite movie is also {favorite_movie}! ")
favorite_game = input("What is your favorite game? ")
print(f"Get out of here! My favorite game is {favorite_game}, too!")
leastfavorite_topping = input("What is your LEAST favoirte pizza topping? ")
print(f"I dislike {leastfavorite_topping} on my pizza! Just like you!")
favorite_class = input("What is your favorite class? ")
print(f"Wow! My favorite class is {favorite_class}, as well!")
print(f"We like all the same things! We shoud become best friends!")